/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Alumno Presencial
 */
public class AltaBaja extends javax.swing.JDialog {

    private JFrameFondo padre;
    /**
     * Creates new form AltaBaja
     */
    public AltaBaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parent=padre;
        initComponents();
        jTFError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        JBLunes = new javax.swing.JRadioButton();
        jBMartes = new javax.swing.JRadioButton();
        jBMiercoles = new javax.swing.JRadioButton();
        jBJueves = new javax.swing.JRadioButton();
        jBViernes = new javax.swing.JRadioButton();
        HoraDia = new javax.swing.JInternalFrame();
        jTFError = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame2.setTitle("Haciendo horario");
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jInternalFrame3.setTitle("Dia de la semana");
        jInternalFrame3.setVisible(true);

        buttonGroup1.add(JBLunes);
        JBLunes.setText("Lunes");

        buttonGroup1.add(jBMartes);
        jBMartes.setText("Martes");

        buttonGroup1.add(jBMiercoles);
        jBMiercoles.setText("Miércoles");

        buttonGroup1.add(jBJueves);
        jBJueves.setText("Jueves");

        buttonGroup1.add(jBViernes);
        jBViernes.setText("Viernes");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JBLunes, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBMartes, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jInternalFrame2.getContentPane().add(jInternalFrame3);

        HoraDia.setTitle("Hora del dia");
        HoraDia.setName("JIFHora"); // NOI18N
        HoraDia.setVisible(true);

        jTFError.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFError.setText("Error por algun motivo");
        jTFError.setEnabled(false);
        jTFError.setFocusable(false);
        jTFError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFErrorActionPerformed(evt);
            }
        });
        HoraDia.getContentPane().add(jTFError, java.awt.BorderLayout.PAGE_END);
        jTFError.getAccessibleContext().setAccessibleName("");

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        jCheckBox1.setText("8:25-9:20");
        jPanel1.add(jCheckBox1);

        jCheckBox2.setText("9:20-10:15");
        jPanel1.add(jCheckBox2);

        jCheckBox3.setText("10:15-11:10");
        jPanel1.add(jCheckBox3);

        jCheckBox4.setText("11:40-12:35");
        jPanel1.add(jCheckBox4);

        jCheckBox5.setText("12:35-13:30");
        jPanel1.add(jCheckBox5);

        jCheckBox6.setText("13:30-14:25");
        jPanel1.add(jCheckBox6);

        jLabel1.setText("Nombre de la asignatura");
        jPanel1.add(jLabel1);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1);

        jBAceptar.setText("ACEPTAR");
        jPanel1.add(jBAceptar);

        HoraDia.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jInternalFrame2.getContentPane().add(HoraDia);

        getContentPane().add(jInternalFrame2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaBaja dialog = new AltaBaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame HoraDia;
    private javax.swing.JRadioButton JBLunes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JRadioButton jBJueves;
    private javax.swing.JRadioButton jBMartes;
    private javax.swing.JRadioButton jBMiercoles;
    private javax.swing.JRadioButton jBViernes;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFError;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
